queue_rules:
  - name: default
    merge_conditions:
      - check-success=tests (mic92, mic92, nixpkgs=channel:nixos-unstable-small)
      - check-success=tests (mic92, mic92, nixpkgs=https://github.com/Mic92/nixpkgs/archive/main.tar.gz)
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
